services:
  - type: web
    name: polymarket-bet-server
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --pre -r requirements.txt
    startCommand: python server.py
